In [25]:
import pymongo
from pymongo import MongoClient
conn = MongoClient()

In [26]:
conn.list_database_names()

['admin', 'config', 'local', 'restaurants']

In [27]:
db = conn.restaurants

In [28]:
db.list_collection_names()

['details']

In [37]:
cur=db.details.find({"borough":"Manhattan", "cuisine":"Irish"} )
for r in cur:
    print(r)

{'_id': ObjectId('643e963693f58d8ae69b9005'), 'address': {'building': '351', 'coord': [-73.98513559999999, 40.7676919], 'street': 'West   57 Street', 'zipcode': '10019'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1409961600000}, 'grade': 'A', 'score': 2}, {'date': {'$date': 1374451200000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1343692800000}, 'grade': 'A', 'score': 12}, {'date': {'$date': 1325116800000}, 'grade': 'A', 'score': 12}], 'name': 'Dj Reynolds Pub And Restaurant', 'restaurant_id': 30191841}
{'_id': ObjectId('643e963693f58d8ae69b905d'), 'address': {'building': '15', 'coord': [-73.9896713, 40.7287978], 'street': 'East    7 Street', 'zipcode': '10003'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1402099200000}, 'grade': 'A', 'score': 8}, {'date': {'$date': 1389225600000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1370995200000}, 'grade': 'A', 'score': 8}, {'date': {'$date': 1337558400000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1326240000000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1313020800000}, 'grade': 'B', 'score': 16}], 'name': "Mcsorley'S Old Ale House", 'restaurant_id': 40365075}
{'_id': ObjectId('643e963693f58d8ae69b9062'), 'address': {'building': '1616', 'coord': [-73.952449, 40.776325], 'street': '2 Avenue', 'zipcode': '10028'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1393545600000}, 'grade': 'A', 'score': 2}, {'date': {'$date': 1377820800000}, 'grade': 'A', 'score': 7}, {'date': {'$date': 1346025600000}, 'grade': 'A', 'score': 7}, {'date': {'$date': 1315958400000}, 'grade': 'A', 'score': 9}], 'name': "Dorrian'S Red Hand Restaurant", 'restaurant_id': 40365239}
{'_id': ObjectId('643e963693f58d8ae69b9072'), 'address': {'building': '146', 'coord': [-74.0056649, 40.7452371], 'street': '10 Avenue', 'zipcode': '10011'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1412208000000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1378771200000}, 'grade': 'A', 'score': 12}, {'date': {'$date': 1360022400000}, 'grade': 'A', 'score': 12}, {'date': {'$date': 1322006400000}, 'grade': 'A', 'score': 11}], 'name': "Moran'S Chelsea", 'restaurant_id': 40365526}
{'_id': ObjectId('643e963693f58d8ae69b9091'), 'address': {'building': '80', 'coord': [-74.0086833, 40.7052024], 'street': 'Beaver Street', 'zipcode': '10005'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1406592000000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1375660800000}, 'grade': 'A', 'score': 7}, {'date': {'$date': 1363219200000}, 'grade': 'A', 'score': 2}, {'date': {'$date': 1343088000000}, 'grade': 'A', 'score': 12}], 'name': 'Killarney Rose', 'restaurant_id': 40366222}
{'_id': ObjectId('643e963693f58d8ae69b9095'), 'address': {'building': '137', 'coord': [-73.98926, 40.7509054], 'street': 'West   33 Street', 'zipcode': '10001'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1408060800000}, 'grade': 'A', 'score': 12}, {'date': {'$date': 1390262400000}, 'grade': 'A', 'score': 5}, {'date': {'$date': 1374624000000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1338422400000}, 'grade': 'A', 'score': 8}, {'date': {'$date': 1327536000000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1318291200000}, 'grade': 'A', 'score': 5}], 'name': 'Blarney Rock', 'restaurant_id': 40366379}
{'_id': ObjectId('643e963693f58d8ae69b909f'), 'address': {'building': '11', 'coord': [-74.0137007, 40.7062029], 'street': 'Trinity Place', 'zipcode': '10006'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1410393600000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1395619200000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1380499200000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1367539200000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1349049600000}, 'grade': 'C', 'score': 43}, {'date': {'$date': 1333324800000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1320883200000}, 'grade': 'A', 'score': 7}], 'name': 'Blarney Stone', 'restaurant_id': 40366574}
{'_id': ObjectId('643e963693f58d8ae69b90b6'), 'address': {'building': '421', 'coord': [-73.99682299999999, 40.753182], 'street': '9 Avenue', 'zipcode': '10001'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1404172800000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1390867200000}, 'grade': 'A', 'score': 8}, {'date': {'$date': 1355270400000}, 'grade': 'A', 'score': 12}, {'date': {'$date': 1325030400000}, 'grade': 'A', 'score': 12}, {'date': {'$date': 1314921600000}, 'grade': 'A', 'score': 12}], 'name': 'Twins Pub', 'restaurant_id': 40367179}
{'_id': ObjectId('643e963693f58d8ae69b9120'), 'address': {'building': '75', 'coord': [-74.0075542, 40.7077614], 'street': 'Maiden Lane', 'zipcode': '10038'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1391040000000}, 'grade': 'A', 'score': 2}, {'date': {'$date': 1376611200000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1344988800000}, 'grade': 'A', 'score': 8}, {'date': {'$date': 1332288000000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1318982400000}, 'grade': 'A', 'score': 8}], 'name': "Jim Brady'S Restaurant", 'restaurant_id': 40369869}
{'_id': ObjectId('643e963693f58d8ae69b9189'), 'address': {'building': '402', 'coord': [-73.9949622, 40.7496446], 'street': '8 Avenue', 'zipcode': '10001'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1419897600000}, 'grade': 'Z', 'score': 17}, {'date': {'$date': 1405296000000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1390521600000}, 'grade': 'A', 'score': 3}, {'date': {'$date': 1376956800000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1359936000000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1325721600000}, 'grade': 'A', 'score': 13}], 'name': 'Molly Wee Pub', 'restaurant_id': 40374277}
{'_id': ObjectId('643e963693f58d8ae69b9190'), 'address': {'building': '800', 'coord': [-73.982506, 40.762621], 'street': '7 Avenue', 'zipcode': '10019'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1411689600000}, 'grade': 'A', 'score': 3}, {'date': {'$date': 1379894400000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1349222400000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1319068800000}, 'grade': 'A', 'score': 7}], 'name': "Rosie O'Grady Restaurant", 'restaurant_id': 40374711}
{'_id': ObjectId('643e963693f58d8ae69b91b6'), 'address': {'building': '906', 'coord': [-73.980002, 40.7659216], 'street': '7 Avenue', 'zipcode': '10019'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1410912000000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1395273600000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1375747200000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1343001600000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1323820800000}, 'grade': 'A', 'score': 7}], 'name': "Pj Carney'S", 'restaurant_id': 40376735}
{'_id': ObjectId('643e963693f58d8ae69b91df'), 'address': {'building': '425', 'coord': [-73.977372, 40.783934], 'street': 'Amsterdam Avenue', 'zipcode': '10024'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1411948800000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1394150400000}, 'grade': 'B', 'score': 19}, {'date': {'$date': 1373414400000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1356480000000}, 'grade': 'B', 'score': 27}, {'date': {'$date': 1340236800000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1327276800000}, 'grade': 'B', 'score': 18}], 'name': "Mcaleer'S Pub", 'restaurant_id': 40379355}
{'_id': ObjectId('643e963693f58d8ae69b923a'), 'address': {'building': '3', 'coord': [-73.97746699999999, 40.757261], 'street': 'East   48 Street', 'zipcode': '10017'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1399939200000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1382572800000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1362700800000}, 'grade': 'A', 'score': 7}, {'date': {'$date': 1340150400000}, 'grade': 'B', 'score': 20}, {'date': {'$date': 1320278400000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1306368000000}, 'grade': 'A', 'score': 13}], 'name': 'Pj Morans', 'restaurant_id': 40384222}
{'_id': ObjectId('643e963693f58d8ae69b92b5'), 'address': {'building': '4946', 'coord': [-73.9206715, 40.8677164], 'street': 'Broadway', 'zipcode': '10034'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1416182400000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1383696000000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1370217600000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1334707200000}, 'grade': 'A', 'score': 3}, {'date': {'$date': 1323216000000}, 'grade': 'A', 'score': 9}], 'name': 'Pipers Kilt', 'restaurant_id': 40388348}
{'_id': ObjectId('643e963693f58d8ae69b9304'), 'address': {'building': '4716', 'coord': [-73.9288969, 40.8644501], 'street': 'Broadway', 'zipcode': '10040'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1401321600000}, 'grade': 'A', 'score': 3}, {'date': {'$date': 1368835200000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1336521600000}, 'grade': 'A', 'score': 7}, {'date': {'$date': 1320019200000}, 'grade': 'A', 'score': 7}], 'name': 'Irish Brigade', 'restaurant_id': 40390820}
{'_id': ObjectId('643e963693f58d8ae69b9312'), 'address': {'building': '103', 'coord': [-73.97894699999999, 40.777789], 'street': 'West   72 Street', 'zipcode': '10023'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1406505600000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1387411200000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1362528000000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1346803200000}, 'grade': 'A', 'score': 12}, {'date': {'$date': 1330473600000}, 'grade': 'A', 'score': 7}, {'date': {'$date': 1317168000000}, 'grade': 'A', 'score': 7}], 'name': "Malachy'S", 'restaurant_id': 40391154}
{'_id': ObjectId('643e963693f58d8ae69b9320'), 'address': {'building': '15', 'coord': [-74.0063787, 40.7108898], 'street': 'Beekman Street', 'zipcode': '10038'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1410739200000}, 'grade': 'A', 'score': 12}, {'date': {'$date': 1397606400000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1382054400000}, 'grade': 'A', 'score': 7}, {'date': {'$date': 1348099200000}, 'grade': 'A', 'score': 4}, {'date': {'$date': 1336435200000}, 'grade': 'A', 'score': 13}], 'name': 'The Beekman', 'restaurant_id': 40391417}
{'_id': ObjectId('643e963693f58d8ae69b934e'), 'address': {'building': '287', 'coord': [-73.9832361, 40.7382721], 'street': '3 Avenue', 'zipcode': '10010'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1394064000000}, 'grade': 'A', 'score': 2}, {'date': {'$date': 1378771200000}, 'grade': 'A', 'score': 6}, {'date': {'$date': 1364774400000}, 'grade': 'A', 'score': 2}, {'date': {'$date': 1348099200000}, 'grade': 'A', 'score': 2}, {'date': {'$date': 1317772800000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1304553600000}, 'grade': 'A', 'score': 4}], 'name': "Molly'S", 'restaurant_id': 40392872}
{'_id': ObjectId('643e963693f58d8ae69b9379'), 'address': {'building': '692', 'coord': [-73.9739876, 40.7518635], 'street': '3 Avenue', 'zipcode': '10017'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1404086400000}, 'grade': 'B', 'score': 17}, {'date': {'$date': 1382572800000}, 'grade': 'B', 'score': 16}, {'date': {'$date': 1368748800000}, 'grade': 'B', 'score': 15}, {'date': {'$date': 1347926400000}, 'grade': 'B', 'score': 23}, {'date': {'$date': 1335139200000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1322784000000}, 'grade': 'B', 'score': 17}], 'name': 'Muldoons Bar', 'restaurant_id': 40393855}
{'_id': ObjectId('643e963693f58d8ae69b93a5'), 'address': {'building': '237', 'coord': [-73.96743500000001, 40.8005319], 'street': 'West  105 Street', 'zipcode': '10025'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1392940800000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1367452800000}, 'grade': 'A', 'score': 12}, {'date': {'$date': 1344902400000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1331683200000}, 'grade': 'C', 'score': 9}, {'date': {'$date': 1318464000000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1309219200000}, 'grade': 'C', 'score': 37}], 'name': 'The Abbey Pub', 'restaurant_id': 40394723}
{'_id': ObjectId('643e963693f58d8ae69b93bd'), 'address': {'building': '61', 'coord': [-73.9898776, 40.7260157], 'street': '2 Avenue', 'zipcode': '10003'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1407801600000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1374451200000}, 'grade': 'A', 'score': 4}, {'date': {'$date': 1344816000000}, 'grade': 'A', 'score': 7}, {'date': {'$date': 1333324800000}, 'grade': 'A', 'score': 5}, {'date': {'$date': 1321833600000}, 'grade': 'A', 'score': 7}], 'name': "Dempsey'S Pub", 'restaurant_id': 40395211}
{'_id': ObjectId('643e963693f58d8ae69b93f2'), 'address': {'building': '150', 'coord': [-73.9838036, 40.7587108], 'street': 'West   47 Street', 'zipcode': '10036'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1410825600000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1391385600000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1369699200000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1332374400000}, 'grade': 'A', 'score': 13}], 'name': 'Langans Bar & Restaurant', 'restaurant_id': 40396246}
{'_id': ObjectId('643e963693f58d8ae69b9403'), 'address': {'building': '5008', 'coord': [-73.917582, 40.868597], 'street': 'Broadway', 'zipcode': '10034'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1421107200000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1409356800000}, 'grade': 'A', 'score': 7}, {'date': {'$date': 1376870400000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1347494400000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1334534400000}, 'grade': 'A', 'score': 10}], 'name': 'Irish Eye Bar', 'restaurant_id': 40396543}
{'_id': ObjectId('643e963693f58d8ae69b9421'), 'address': {'building': '768', 'coord': [-73.98796700000001, 40.764263], 'street': '9 Avenue', 'zipcode': '10019'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1415923200000}, 'grade': 'A', 'score': 12}, {'date': {'$date': 1383523200000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1350518400000}, 'grade': 'A', 'score': 8}, {'date': {'$date': 1338422400000}, 'grade': 'A', 'score': 13}], 'name': "Mccoy'S Pub", 'restaurant_id': 40397359}
{'_id': ObjectId('643e963693f58d8ae69b947e'), 'address': {'building': '18', 'coord': [-73.9862593, 40.7481711], 'street': 'West   33 Street', 'zipcode': '10001'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1418083200000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1386288000000}, 'grade': 'A', 'score': 12}, {'date': {'$date': 1355184000000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1340668800000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1327881600000}, 'grade': 'A', 'score': 12}], 'name': "Foley'S N.Y. Pub And Restaurant", 'restaurant_id': 40399523}
{'_id': ObjectId('643e963693f58d8ae69b94bf'), 'address': {'building': '267', 'coord': [-73.980271, 40.750972], 'street': 'Madison Avenue', 'zipcode': '10016'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1414627200000}, 'grade': 'A', 'score': 7}, {'date': {'$date': 1401840000000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1386633600000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1367280000000}, 'grade': 'B', 'score': 17}, {'date': {'$date': 1333411200000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1321488000000}, 'grade': 'A', 'score': 9}], 'name': "Mulligan'S Pub", 'restaurant_id': 40400559}
{'_id': ObjectId('643e963693f58d8ae69b94ce'), 'address': {'building': '209', 'coord': [-73.9905498, 40.7275824], 'street': 'East    5 Street', 'zipcode': '10003'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1392854400000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1375747200000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1353974400000}, 'grade': 'B', 'score': 19}, {'date': {'$date': 1318896000000}, 'grade': 'A', 'score': 5}, {'date': {'$date': 1309910400000}, 'grade': 'B', 'score': 16}], 'name': 'The Scratcher Cafe', 'restaurant_id': 40400810}
{'_id': ObjectId('643e963693f58d8ae69b94d6'), 'address': {'building': '40', 'coord': [-74.0102663, 40.7057236], 'street': 'Exchange Place', 'zipcode': '10005'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1417996800000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1400630400000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1383696000000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1365379200000}, 'grade': 'A', 'score': 11}, {'date': {'$date': 1346716800000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1333670400000}, 'grade': 'A', 'score': 13}], 'name': 'Irish Punt', 'restaurant_id': 40400976}
{'_id': ObjectId('643e963693f58d8ae69b94d8'), 'address': {'building': '50', 'coord': [-73.9782432, 40.7530749], 'street': 'East   43 Street', 'zipcode': '10017'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1397433600000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1378771200000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1359417600000}, 'grade': 'A', 'score': 12}, {'date': {'$date': 1345075200000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1312761600000}, 'grade': 'A', 'score': 13}], 'name': "Annie Moore'S Restaurant", 'restaurant_id': 40400992}
{'_id': ObjectId('643e963693f58d8ae69b9527'), 'address': {'building': '330', 'coord': [-73.9933113, 40.7478417], 'street': '7 Avenue', 'zipcode': '10001'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1409702400000}, 'grade': 'A', 'score': 10}, {'date': {'$date': 1394668800000}, 'grade': 'A', 'score': 7}, {'date': {'$date': 1360540800000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1328659200000}, 'grade': 'A', 'score': 12}, {'date': {'$date': 1317772800000}, 'grade': 'A', 'score': 13}], 'name': 'The Triple Crown', 'restaurant_id': 40402231}
{'_id': ObjectId('643e963693f58d8ae69b95e3'), 'address': {'building': '14', 'coord': [-73.9778118, 40.7561728], 'street': 'East   47 Street', 'zipcode': '10017'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1404086400000}, 'grade': 'A', 'score': 12}, {'date': {'$date': 1389830400000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1355097600000}, 'grade': 'A', 'score': 7}, {'date': {'$date': 1342569600000}, 'grade': 'A', 'score': 11}], 'name': "Connolly'S Pub", 'restaurant_id': 40512865}
{'_id': ObjectId('643e963693f58d8ae69b965e'), 'address': {'building': '118', 'coord': [-73.9840852, 40.7268832], 'street': 'St Marks Place', 'zipcode': '10009'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1400630400000}, 'grade': 'B', 'score': 14}, {'date': {'$date': 1376697600000}, 'grade': 'A', 'score': 9}, {'date': {'$date': 1358294400000}, 'grade': 'B', 'score': 26}, {'date': {'$date': 1333670400000}, 'grade': 'B', 'score': 0}], 'name': "St. Dymphna'S", 'restaurant_id': 40535409}
{'_id': ObjectId('643e963693f58d8ae69b9675'), 'address': {'building': '29', 'coord': [-73.98830389999999, 40.7290695], 'street': 'St Marks Place', 'zipcode': '10003'}, 'borough': 'Manhattan', 'cuisine': 'Irish', 'grades': [{'date': {'$date': 1407196800000}, 'grade': 'A', 'score': 13}, {'date': {'$date': 1391385600000}, 'grade': 'A', 'score': 12}, {'date': {'$date': 1334620800000}, 'grade': 'A', 'score': 10}], 'name': 'Bull Mccabes', 'restaurant_id': 40537686}

In [30]:
import pandas as pd

In [40]:
data = pd.DataFrame(list(db.details.find(
    {"borough": "Manhattan", "cuisine": "Irish"})))
data.head()

,_id,address,borough,cuisine,grades,name,restaurant_id
0,643e963693f58d8ae69b9005,"{'building': '351', 'coord': [-73.985135599999...",Manhattan,Irish,"[{'date': {'$date': 1409961600000}, 'grade': '...",Dj Reynolds Pub And Restaurant,30191841
1,643e963693f58d8ae69b905d,"{'building': '15', 'coord': [-73.9896713, 40.7...",Manhattan,Irish,"[{'date': {'$date': 1402099200000}, 'grade': '...",Mcsorley'S Old Ale House,40365075
2,643e963693f58d8ae69b9062,"{'building': '1616', 'coord': [-73.952449, 40....",Manhattan,Irish,"[{'date': {'$date': 1393545600000}, 'grade': '...",Dorrian'S Red Hand Restaurant,40365239
3,643e963693f58d8ae69b9072,"{'building': '146', 'coord': [-74.0056649, 40....",Manhattan,Irish,"[{'date': {'$date': 1412208000000}, 'grade': '...",Moran'S Chelsea,40365526
4,643e963693f58d8ae69b9091,"{'building': '80', 'coord': [-74.0086833, 40.7...",Manhattan,Irish,"[{'date': {'$date': 1406592000000}, 'grade': '...",Killarney Rose,40366222

In [32]:
data_1 = pd.json_normalize(db.details.find({"borough": "Manhattan", "cuisine": "Irish"}), "grades", ['borough', 'cuisine', 'name'],
                    record_prefix='grades_')

In [33]:
data_1.tail()

,grades_grade,grades_score,grades_date.$date,borough,cuisine,name
531,A,8,1323820800000,Manhattan,Irish,Peter Dillon'S Bar
532,A,10,1309219200000,Manhattan,Irish,Peter Dillon'S Bar
533,A,3,1394755200000,Manhattan,Irish,The Irish Pub
534,A,11,1362528000000,Manhattan,Irish,The Irish Pub
535,A,7,1329436800000,Manhattan,Irish,The Irish Pub